packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.15.0
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^3.7.0
  '@types/node': ^24.0.3
  '@unocss/reset': ^66.2.3
  '@vueuse/core': ^13.4.0
  bumpp: ^10.2.0
  eslint: ^9.29.0
  floating-vue: ^5.2.2
  lint-staged: ^16.1.2
  pinia: ^3.0.3
  pnpm: ^10.12.1
  simple-git-hooks: ^2.13.0
  tsx: ^4.20.3
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.2.3
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.6
  vitepress-plugin-group-icons: ^1.6.0
  vitest: ^3.2.4
  vue: ^3.5.17
